### ISSUE TITLE
No Match Function in Open Class

### ISSUE THREAD

**Issue by ravijha65** [martinlevesque/ptp-plusplus#1]
hi,
Thanks for the code but there is compilation in statsCollector.cc file in line no. 80. during the build it's showing  "Description  Resource    Path    Location    Type
no matching function for call to ‘std::basic_ofstream<char>::open(std::basic_stringstream<char>::__string_type, const openmode&)’   StatsCollector.cc   /PTP/src/util   line 80 C/C++ Problem" as error."
here i am using omnet4.3, inet2.6 and ubuntu linux operating system.
Please help me out of this issue.

**Comment by martinlevesque** [comment]
hey,

Is your c++ standard library installed ?

Martin

2016-02-09 1:49 GMT-05:00 ravijha65 notifications@github.com:

> hi,
> Thanks for the code but there is compilation in statsCollector.cc file in
> line no. 80. during the build it's showing "Description Resource Path
> Location Type
> no matching function for call to
> ‘std::basic_ofstream::open(std::basic_stringstream::__string_type, const
> openmode&)’ StatsCollector.cc /PTP/src/util line 80 C/C++ Problem" as
> error."
> here i am using omnet4.3, inet2.6 and ubuntu linux operating system.
> Please help me out of this issue.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/martinlevesque/ptp-plusplus/issues/1.

## 

---

Martin Lévesque
